site_name: "test"
site_description: 

nav:
  - Introduction: index.md
  - Architecture Decisions:
      - Overview: adrs/index.md
      - "0001 Use React": adrs/0001-use-react.md

plugins:
  - techdocs-core
